# Use Ubuntu 22.04 as the base image
FROM nvidia/cuda:12.9.1-cudnn-devel-ubuntu24.04

# Prevent prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Update the package lists and install the required packages
RUN apt-get update && \
    apt-get install -y \
    cmake \
    libopencv-dev

    # Optional: Add other common development tools if needed
    # git \
    # vim \
    # curl \
    # && apt-get clean && \
    # rm -rf /var/lib/apt/lists/*
