# Use Ubuntu 22.04 as the base image
FROM ubuntu:22.04

# Prevent prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Update the package lists and install the required packages
RUN apt-get update && \
    apt-get install -y \
    build-essential \
    python3-pip \
    cmake \
    pkg-config 
    # Optional: Add other common development tools if needed
    # git \
    # vim \
    # curl \
    # && apt-get clean && \
    # rm -rf /var/lib/apt/lists/*

RUN pip install conan